import pygame

player = pygame.image.load("images/cars/jeffcar.png").convert_alpha()
enemy = pygame.image.load("images/cars/enemycar.png").convert_alpha()
spikes = pygame.image.load("images/spikes.png").convert_alpha()
barrier = pygame.image.load("images/barrier.png").convert_alpha()
banana = pygame.image.load("images/banana.png").convert_alpha()
car3d = pygame.image.load("images/cars/car3d.png").convert_alpha()
enemy3d = pygame.image.load("images/cars/enemy3d.png").convert_alpha()
car3d = pygame.image.load("images/cars/car3d.png").convert_alpha()
enemy3d = pygame.image.load("images/cars/enemy3d.png").convert_alpha()
ball = pygame.image.load("images/ballenhanced.png").convert_alpha()
tree = pygame.image.load("images/tree.png").convert_alpha()
police = pygame.image.load("images/cars/police.png").convert_alpha()
bike = pygame.image.load("images/cars/bike.png").convert_alpha()
castle = pygame.image.load("images/castel.png").convert_alpha()
newcar = pygame.image.load("images/cars/wierdcar.png").convert_alpha()
plane = pygame.image.load("images/cars/plane.png").convert_alpha()
skateboard = pygame.image.load("images/cars/skateboard.png").convert_alpha()
tire = pygame.image.load("images/tire.png").convert_alpha()
guideArrow = pygame.image.load("images/arrow.png").convert_alpha()
speedBump = pygame.image.load("images/spedbump.png").convert_alpha()
coin = pygame.image.load("images/coin.png").convert_alpha()

mapone = pygame.image.load("images/maps/testmapone.png").convert_alpha()